name: Context

on: [push, workflow_dispatch]

jobs:
  context:
    name: Check context
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    timeout-minutes: 3

    steps:
    - name: echo github context
      run: |
        echo "${{ toJson(github) }}"
        echo "github.event: ${{ toJson(github.event) }}"
        echo "github.ref: ${{ github.ref }}"
        echo "github.ref_name: ${{ github.ref_name }}"
        echo "github.sha: ${{ github.sha }}"
