name: Expression

on:
  workflow_dispatch:

jobs:
  context:
    name: Check expression
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    timeout-minutes: 3

    steps:
    - name: sleep
      run: sleep 10

    - name: exit
      run: exit 1

    - name: Expression 1
      if: failure()
      run: echo "Step executed"

    - name: Expression 2
      if: cancelled()
      run: echo "Step executed"

    - name: Expression 3
      if: failure() || cancelled()
      run: echo "Step executed"

    - name: Expression 4
      if: ${{ failure() }} || ${{ cancelled() }}
      run: echo "Step executed"
